/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.dicontainer;

import ru.nsu.fit.dicontainer.client.PartyOrganizer;
import ru.nsu.fit.dicontainer.context.ApplicationContext;
import ru.nsu.fit.dicontainer.factory.BeanFactory;

public class App {
  public ApplicationContext run(){
    ApplicationContext applicationContext = new ApplicationContext();
    BeanFactory beanFactory = new BeanFactory(applicationContext);
    applicationContext.setBeanFactory(beanFactory);

    return applicationContext;
  }

  public static void main(String[] args) {
    App app = new App();
    ApplicationContext context = app.run();

    PartyOrganizer partyOrganizer = context.getBean(PartyOrganizer.class);
    partyOrganizer.prepareToCelebration();
  }
}
